@startuml
'https://plantuml.com/class-diagram

abstract ChoVay
{
    int hanMucVay
    String tenNguoiDuyet, chucVu, duAnVay
    + ATM khoanVayKeTiep(ATM keTiep)
    + vayTien(int soTienVay)
}

class PhoTruongPhong

class ChuTich

ChoVay <|--- PhoTruongPhong
ChoVay <---* PhoTruongPhong : keTiep

ChoVay <|--- ChuTich

@enduml